name: Scriptoteket
url: http://localhost:4000
site:
  url: http://localhost:4000
permalink: /blog/:year/:month/:day/:title.html
excerpt_separator: "<!-- more -->"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
feed:
  path: /blog/feed.xml
paginate: 10
paginate_path: '/blog/page:num/'
# pygments: true
authors:
  dmheggo:
    name: Dan Michael O. Heggø
    display_name: Dan Michael
    gravatar: c66919cb194f96c696c1da0c47354a6a
    email: dmheggo@ub.uio.no
    uio: personer/ureal/urealpublikum/dmheggo/
    twitter: danmichaelo
    github: danmichaelo
